##
##  Makefile -- Build procedure for sample openqm Apache module
##  Autogenerated via ``apxs -n openqm -g''.
##

builddir=.
top_srcdir=/usr/share/apache2
top_builddir=/usr/share/apache2
include /usr/share/apache2/build/special.mk

#   the used tools
APACHECTL=apachectl
OPENQM_ROOT=/home/thierry/openqm

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
INCLUDES=-I$(OPENQM_ROOT)/openqm.account/SYSCOM -I$(OPENQM_ROOT)/openqm.account/gplsrc
#LIBS=
LT_LDFLAGS=$(OPENQM_ROOT)/openqm.account/bin/qmclilib64.o

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_openqm.o mod_openqm.lo mod_openqm.slo mod_openqm.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/openqm

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

